spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&characterEncoding=utf8&autoReconnect=true&useUnicode=true&useAffectedRows=TRUE&serverTimezone=UTC
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  path: /var/log/otc
  pattern:
    console: '%d %-5level %logger : %msg%n'
    file: '%d %level [%thread] %logger{36} [%file : %line] %msg%n'
  level:
    com.example: DEBUG